const $=(id)=>document.getElementById(id);const state={items:[],address:null,customerRate:null,opsRate:null,requested:false,verified:false,packed:false,labelBought:false,dispatched:false,trackingIndex:0,tracking:null};
const itemData={sneaker:{name:'Jordan 1 High',type:'Sneakers',weight:1.45,value:320,dims:[36,25,15]},hoodie:{name:'Heavyweight Hoodie',type:'Apparel',weight:0.85,value:145,dims:[34,28,9]}};
const blockedCountries=['DE'];
const trackingStages=[
{status:'Requested',title:'Fulfillment request received.',subtitle:'The Toronto fulfillment team has your request.',event:'Shipment requested by customer.'},
{status:'Packing',title:'Your items are being packed.',subtitle:'The fulfillment team verified your order and is preparing the parcel.',event:'Items verified and packing started.'},
{status:'Label created',title:'Your shipping label is ready.',subtitle:'A tracking number has been assigned to the parcel.',event:'Carrier label created in Toronto.'},
{status:'In transit',title:'Your shipment is on the way.',subtitle:'The parcel has been handed to the carrier.',event:'Parcel accepted by carrier in Toronto.'},
{status:'In transit',title:'Moving through the carrier network.',subtitle:'Your shipment is progressing toward the destination.',event:'Shipment processed at carrier facility.'},
{status:'Delivered',title:'Delivered.',subtitle:'Your shipment has reached its destination.',event:'Delivered to destination.'}
];

document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$(btn.dataset.tab).classList.add('active')}));

document.querySelectorAll('.item').forEach(btn=>btn.addEventListener('click',()=>{const id=btn.dataset.item;btn.classList.toggle('selected');state.items=btn.classList.contains('selected')?[...new Set([...state.items,id])]:state.items.filter(x=>x!==id);updatePackage();resetAfterItems()}));

function updatePackage(){const count=state.items.length;$('selectionCount').textContent=`${count} selected`;$('snapItems').textContent=count?state.items.map(x=>itemData[x].type).join(' + '):'None';if(!count){$('packageName').textContent='Select items';$('packageWeight').textContent='—';$('packageValue').textContent='—';$('addressPanel').classList.add('disabled');return}const p=packageEstimate();$('packageName').textContent=count===2?'Combined shipment':itemData[state.items[0]].type+' parcel';$('packageWeight').textContent=`${p.weight.toFixed(2)} kg`;$('packageValue').textContent=`C$${p.value}`;$('addressPanel').classList.remove('disabled');$('addressChip').textContent='Ready';$('addressChip').className='chip success'}
function packageEstimate(){const weight=state.items.reduce((s,x)=>s+itemData[x].weight,0)+(state.items.length>1?.35:.2);const value=state.items.reduce((s,x)=>s+itemData[x].value,0);let dims=state.items.length===2?[42,32,24]:itemData[state.items[0]]?.dims||[30,20,10];return{weight,value,dims}}
function resetAfterItems(){state.address=null;state.customerRate=null;$('ratesPanel').classList.add('disabled');$('confirmPanel').classList.add('disabled');$('customerRates').innerHTML='';$('rateEmpty').classList.remove('hidden');$('requestShipment').disabled=true;$('snapDestination').textContent='Not set';$('snapService').textContent='Not selected';}

$('addressForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);state.address=Object.fromEntries(fd.entries());const country=state.address.country;if(blockedCountries.includes(country)){showBlocked();return}const rates=getRates(country,packageEstimate());renderCustomerRates(rates);$('snapDestination').textContent=`${state.address.city}, ${state.address.region}`;$('ratesPanel').classList.remove('disabled');$('ratesChip').textContent=`${rates.length} services`;$('ratesChip').className='chip success'});
function showBlocked(){$('ratesPanel').classList.remove('disabled');$('customerRates').innerHTML='<div class="empty"><strong>Shipping unavailable</strong><p>This destination is blacklisted in Admin → Shipping → Service Areas.</p></div>';$('rateEmpty').classList.add('hidden');$('ratesChip').textContent='Blocked';$('ratesChip').className='chip warning';$('confirmPanel').classList.add('disabled');$('destinationMessage').textContent='This destination is currently restricted by your shipping settings.';$('snapDestination').textContent=`${state.address.city}, ${state.address.region}`;}

function getRates(country,pkg,ops=false){let rates;if(country==='CA')rates=[{carrier:'Chit Chats',service:'Canada Tracked',days:'2–6 business days',price:ops?10.95:11.45,tag:'Cheapest'},{carrier:'Canada Post',service:'Expedited Parcel',days:'2–5 business days',price:ops?14.8:15.35,tag:'Recommended'},{carrier:'Purolator',service:'Ground',days:'1–3 business days',price:ops?17.4:18.1,tag:''},{carrier:'UPS',service:'Standard',days:'1–3 business days',price:ops?18.6:19.25,tag:'Fastest'}];else if(country==='US')rates=[{carrier:'Chit Chats',service:'U.S. Tracked / USPS',days:'3–7 business days',price:ops?13.7:14.35,tag:'Cheapest'},{carrier:'UPS',service:'Standard',days:'3–5 business days',price:ops?22.7:23.8,tag:'Recommended'},{carrier:'FedEx',service:'International Ground',days:'3–6 business days',price:ops?24.9:26.1,tag:''},{carrier:'DHL',service:'Express',days:'1–2 business days',price:ops?43.2:44.95,tag:'Fastest'}];else rates=[{carrier:'Canada Post',service:'International Tracked',days:'6–12 business days',price:ops?34.5:36.25,tag:'Cheapest'},{carrier:'DHL',service:'Express Worldwide',days:'2–4 business days',price:ops?58.2:60.1,tag:'Fastest'},{carrier:'UPS',service:'Worldwide Saver',days:'3–5 business days',price:ops?55.1:57.4,tag:'Recommended'}];const dimensional=(pkg.dims[0]*pkg.dims[1]*pkg.dims[2])/5000;const billable=Math.max(pkg.weight,dimensional);const bump=Math.max(0,billable-3)*1.35;return rates.map((r,i)=>({...r,id:`r${i}`,price:+(r.price+bump).toFixed(2)}))}
function renderCustomerRates(rates){$('rateEmpty').classList.add('hidden');$('customerRates').innerHTML=rates.map(r=>`<button class="rate" data-rate="${r.id}"><div><strong>${r.carrier}</strong>${r.tag?`<span class="tag">${r.tag}</span>`:''}<small>${r.service}</small></div><small>${r.days}</small><small>Tracked</small><b>C$${r.price.toFixed(2)}</b></button>`).join('');document.querySelectorAll('#customerRates .rate').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('#customerRates .rate').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');state.customerRate=rates.find(r=>r.id===btn.dataset.rate);prepareConfirmation()}))}
function prepareConfirmation(){const a=state.address,r=state.customerRate;$('confirmPanel').classList.remove('disabled');$('confirmChip').textContent='Ready';$('confirmChip').className='chip success';$('confirmAddress').textContent=`${a.address}, ${a.city}, ${a.region} ${a.postal}`;$('confirmService').textContent=`${r.carrier} · ${r.service}`;$('confirmItems').textContent=state.items.map(x=>itemData[x].type).join(' + ');$('confirmPrice').textContent=`C$${r.price.toFixed(2)}`;$('snapService').textContent=r.carrier;$('requestShipment').disabled=false}

$('requestShipment').addEventListener('click',()=>{state.requested=true;state.trackingIndex=0;state.tracking=null;$('trackingPanel').classList.remove('hidden');$('confirmPanel').classList.add('disabled');$('snapStatus').textContent='Requested';createOpsOrder();renderTracking();toast('Fulfillment request sent to Toronto ops')});
function createOpsOrder(){const a=state.address,p=packageEstimate();$('opsPlaceholder').classList.add('hidden');$('opsOrder').classList.remove('hidden');$('queueEmpty').classList.add('hidden');$('queueOrder').classList.remove('hidden');$('openKpi').textContent='1';$('queueCustomer').textContent=a.name;$('queueSummary').textContent=state.items.map(x=>itemData[x].type).join(' + ');$('queueDestination').textContent=`${a.city}, ${a.region}`;$('opsName').textContent=a.name;$('opsDestination').textContent=`${a.address}, ${a.city}, ${a.region} ${a.postal}, ${a.country}`;$('opsRequestedService').textContent=`${state.customerRate.carrier} · ${state.customerRate.service}`;$('opsRequestedPrice').textContent=`C$${state.customerRate.price.toFixed(2)}`;$('opsItems').innerHTML=state.items.map(id=>`<div class="ops-item"><div><strong>${itemData[id].name}</strong><span>${itemData[id].type}</span></div><strong>C$${itemData[id].value}</strong></div>`).join('');$('opsAddress').innerHTML=`<strong>${a.name}</strong><br>${a.address}<br>${a.city}, ${a.region} ${a.postal}<br>${countryName(a.country)}<br>${a.phone}`;$('actualWeight').value=p.weight.toFixed(2);$('length').value=p.dims[0];$('width').value=p.dims[1];$('height').value=p.dims[2];$('declaredValue').value=p.value;$('labelDest').textContent=`${a.city}, ${a.region}`}

$('verifyBtn').addEventListener('click',()=>{state.verified=true;$('verifyChip').textContent='Verified';$('verifyChip').className='chip success';$('packingSection').classList.remove('disabled');$('packingChip').textContent='Ready to pack';$('packingChip').className='chip success';advanceCustomerTo(1);toast('Order verified')});
$('savePackage').addEventListener('click',()=>{state.packed=true;const pkg={weight:+$('actualWeight').value,dims:[+$('length').value,+$('width').value,+$('height').value],value:+$('declaredValue').value};const rates=getRates(state.address.country,pkg,true);renderOpsRates(rates);$('opsRatesSection').classList.remove('disabled');$('opsRatesChip').textContent=`${rates.length} live-style quotes`;$('opsRatesChip').className='chip success';$('packingChip').textContent='Packed';$('packingChip').className='chip success';const cheapest=Math.min(...rates.map(r=>r.price));$('rateDelta').textContent=`Customer selected C$${state.customerRate.price.toFixed(2)}. Current cheapest operational rate is C$${cheapest.toFixed(2)}. Demo rates are illustrative.`;toast('Package saved and re-rated')});
function renderOpsRates(rates){$('opsRates').innerHTML=rates.map(r=>`<button class="rate ops-rate" data-rate="${r.id}"><div><strong>${r.carrier}</strong>${r.tag?`<span class="tag">${r.tag}</span>`:''}<small>${r.service}</small></div><small>${r.days}</small><small>Tracking + label</small><b>C$${r.price.toFixed(2)}</b></button>`).join('');document.querySelectorAll('.ops-rate').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.ops-rate').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');state.opsRate=rates.find(r=>r.id===btn.dataset.rate);prepareLabel()}))}
function prepareLabel(){const r=state.opsRate;$('labelSection').classList.remove('disabled');$('labelChip').textContent='Ready to buy';$('labelChip').className='chip success';$('labelCarrier').textContent=r.carrier;$('labelService').textContent=r.service;$('labelPostage').textContent=`C$${r.price.toFixed(2)}`;$('labelTotal').textContent=`C$${r.price.toFixed(2)}`;$('buyLabel').disabled=false}
$('buyLabel').addEventListener('click',()=>{state.labelBought=true;state.tracking=trackingNumber(state.opsRate.carrier);$('labelTracking').textContent=state.tracking;$('opsTracking').textContent=state.tracking;$('trackingNumber').textContent=state.tracking;$('labelChip').textContent='Purchased';$('labelChip').className='chip success';$('printLabel').disabled=false;$('dispatchSection').classList.remove('disabled');$('dispatchChip').textContent='Ready for handoff';$('dispatchChip').className='chip success';$('dispatchBtn').disabled=false;advanceCustomerTo(2);toast('Label purchased')});
$('printLabel').addEventListener('click',()=>toast('4×6 label sent to demo printer'));
$('dispatchBtn').addEventListener('click',()=>{state.dispatched=true;$('dispatchBtn').disabled=true;$('advanceTracking').disabled=false;$('dispatchChip').textContent='In transit';$('dispatchChip').className='chip success';$('queueStatus').textContent='Shipped';$('queueStatus').className='chip success';$('opsStatus').textContent='In transit';$('opsStatus').className='chip success';$('openKpi').textContent='0';$('shippedKpi').textContent='1';advanceCustomerTo(3);toast('Shipment handed to carrier')});
$('advanceTracking').addEventListener('click',()=>{if(state.trackingIndex<trackingStages.length-1){advanceCustomerTo(state.trackingIndex+1);if(state.trackingIndex===trackingStages.length-1){$('advanceTracking').disabled=true;$('dispatchChip').textContent='Delivered';$('currentScan').textContent='Delivered';toast('Shipment delivered')}else toast('Tracking advanced')}});

function advanceCustomerTo(i){state.trackingIndex=i;$('currentScan').textContent=trackingStages[i].status;renderTracking()}
function renderTracking(){const s=trackingStages[state.trackingIndex];$('customerStatus').textContent=s.status;$('customerStatus').className='chip '+(s.status==='Delivered'?'success':s.status==='Requested'?'warning':'success');$('trackingTitle').textContent=s.title;$('trackingSubtitle').textContent=s.subtitle;$('trackingCarrier').textContent=state.opsRate?`${state.opsRate.carrier} · ${state.opsRate.service}`:state.customerRate?`${state.customerRate.carrier} requested`:'Carrier pending';$('trackingNumber').textContent=state.tracking||'Pending';$('snapStatus').textContent=s.status;$('trackingProgress').innerHTML=trackingStages.map((_,idx)=>`<div class="progress-step ${idx<=state.trackingIndex?'done':''}"></div>`).join('');$('trackingEvents').innerHTML=trackingStages.slice(0,state.trackingIndex+1).reverse().map((e,idx)=>`<div class="event"><small>${idx===0?'Latest update':'Earlier'}</small><div><strong>${e.event}</strong><small>${e.status==='Delivered'?'Destination':'Toronto / carrier network'}</small></div></div>`).join('')}
function trackingNumber(carrier){const p={"Chit Chats":'CH','Canada Post':'CP','Purolator':'PUR','UPS':'1Z','FedEx':'FDX','DHL':'DHL'}[carrier]||'TRK';return p+Math.random().toString().slice(2,14)}
function countryName(code){return{CA:'Canada',US:'United States',GB:'United Kingdom',DE:'Germany',FR:'France',AU:'Australia',JP:'Japan'}[code]||code}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
